version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp"  # Required only for using Pi-hole as a DHCP server
      - "80:80/tcp"
    environment:
# List of timezones to use --- https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: 'Africa/Johannesburg'
      WEBPASSWORD: 'supersecretpassword'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN
    restart:
      unless-stopped
