network:
   version: 2
   ethernets:
     ens18:
       dhcp4: False
       addresses:
          - 192.168.0.246/16
       gateway4: 192.168.0.1
       nameservers:
          addresses: [8.8.8.8,4.4.4.4]
